### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by arharvard** [code-for-montana/pyrs990#4]
Hello,

I installed the package, but cannot download form 990 for a sample EIN. 
Any chance for a sample code for a specific EIN between 2015-2021?

THanks

**Comment by glesica** [comment]
Unfortunately, the IRS changed how they host the data files, so this package no longer works for downloads. Sorry for that. I will make a note to update the README.

**Comment by arharvard** [comment]
Thanks for letting me know! 

Is there a way to use this on XML directly if they are in a local folder?

**Comment by glesica** [comment]
I don't actually remember, I wrote this quite awhile ago. I will take a quick look to see if I can easily change it to work around the data hosting issue.

**Comment by arharvard** [comment]
Thank you!
